from typing import Any, List, Optional, Tuple
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_, desc, func
from sqlalchemy.dialects.postgresql import insert
from common.databases.models.message import Message
from jobCollectionWebApi.schemas.message_schema import MessageCreate, MessageUpdate
from .base import CRUDBase

class CRUDMessage(CRUDBase[Message, MessageCreate, MessageUpdate]):
    """消息 CRUD"""

    async def get_my_messages(
        self,
        db: AsyncSession,
        receiver_id: int,
        skip: int = 0,
        limit: int = 20,
        *,
        unread_only: bool = False,
        category: Optional[str] = None,
        status: Optional[str] = None,
    ) -> List[Message]:
        """获取我的消息列表"""
        conditions = [Message.receiver_id == receiver_id]
        if unread_only:
            conditions.append(Message.is_read.is_(False))
        if category:
            conditions.append(Message.category == category)
        if status:
            conditions.append(Message.status == status)
        stmt = (
            select(Message)
            .where(*conditions)
            .order_by(Message.created_at.desc())
            .offset(skip)
            .limit(limit)
        )
        result = await db.execute(stmt)
        return result.scalars().all()

    async def get_my_messages_page(
        self,
        db: AsyncSession,
        *,
        receiver_id: int,
        skip: int = 0,
        limit: int = 20,
        unread_only: bool = False,
        category: Optional[str] = None,
        status: Optional[str] = None,
    ) -> tuple[List[Message], int]:
        conditions = [Message.receiver_id == receiver_id]
        if unread_only:
            conditions.append(Message.is_read.is_(False))
        if category:
            conditions.append(Message.category == category)
        if status:
            conditions.append(Message.status == status)
        total = await db.scalar(select(func.count(Message.id)).where(*conditions))
        rows = await self.get_my_messages(
            db,
            receiver_id=receiver_id,
            skip=skip,
            limit=limit,
            unread_only=unread_only,
            category=category,
            status=status,
        )
        return rows, int(total or 0)

    async def create_or_get(self, db: AsyncSession, payload: Any) -> Tuple[Message, bool]:
        """Atomically create a system notification or return its deduplicated row.

        ``dedupe_key`` is generated by the source task and protected by a
        database unique constraint, so concurrent Celery retries cannot create
        two message-center rows.
        """
        values = payload.to_model_values()
        dedupe_key = values.get("dedupe_key")
        if not dedupe_key:
            obj = Message(**values)
            db.add(obj)
            await db.flush()
            await db.refresh(obj)
            return obj, True

        statement = (
            insert(Message)
            .values(**values)
            .on_conflict_do_nothing(index_elements=[Message.dedupe_key])
            .returning(Message.id)
        )
        created_id = (await db.execute(statement)).scalar_one_or_none()
        if created_id is not None:
            created = await self.get(db, id=created_id)
            return created, True

        existing = await db.execute(select(Message).where(Message.dedupe_key == dedupe_key))
        message = existing.scalar_one()
        return message, False

    async def get_unread_count(self, db: AsyncSession, receiver_id: int) -> int:
        """获取未读消息数"""
        stmt = select(func.count(Message.id)).where(
            and_(Message.receiver_id == receiver_id, Message.is_read == False)
        )
        result = await db.execute(stmt)
        return result.scalar()

    async def mark_all_read(self, db: AsyncSession, receiver_id: int) -> None:
        """全部标记为已读"""
        # Note: bulk update in simple way
        # update(Message).where(...).values(is_read=True)
        from sqlalchemy import update
        stmt = (
            update(Message)
            .where(and_(Message.receiver_id == receiver_id, Message.is_read == False))
            .values(is_read=True)
        )
        await db.execute(stmt)
        await db.commit()

message = CRUDMessage(Message)
