[program:job-api]
directory=/opt/job/jobCollectionWebApi
command=/opt/job/jobCollectionWebApi/venv/bin/uvicorn main:app --host 127.0.0.1 --port 8000 --workers 4
user=root
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/job-api.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20
environment=PYTHONPATH="/opt/job",ENVIRONMENT="production"

[program:job-admin]
directory=/opt/job/jobCollectionWebApi
command=/opt/job/jobCollectionWebApi/venv/bin/uvicorn main_admin:app --host 127.0.0.1 --port 8002 --workers 1
user=root
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/job-admin.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20
environment=PYTHONPATH="/opt/job",ENVIRONMENT="production"

[program:job-celery-realtime]
directory=/opt/job/jobCollectionWebApi
command=/opt/job/jobCollectionWebApi/venv/bin/celery -A core.celery_app worker -Q realtime -l info -c 4 --hostname=worker_realtime@%%h
user=root
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/job-celery-realtime.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20
environment=PYTHONPATH="/opt/job",ENVIRONMENT="production"

[program:job-celery-batch]
directory=/opt/job/jobCollectionWebApi
command=/opt/job/jobCollectionWebApi/venv/bin/celery -A core.celery_app worker -Q batch -l info -c 2 --hostname=worker_batch@%%h
user=root
autostart=false
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/job-celery-batch.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20
environment=PYTHONPATH="/opt/job",ENVIRONMENT="production"

[program:job-celery-beat]
directory=/opt/job/jobCollectionWebApi
command=/opt/job/jobCollectionWebApi/venv/bin/celery -A core.celery_app beat -l info --schedule /var/lib/job/celerybeat-schedule
user=root
autostart=false
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/job-celery-beat.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20
environment=PYTHONPATH="/opt/job",ENVIRONMENT="production"
