#!/usr/bin/env bash
set -Eeuo pipefail

repository_url=${1:?repository URL is required}
commit=${2:?commit SHA is required}
release_id=${3:?release id is required}
server_name=${4:?server name is required}

base_dir=/opt/job
release_dir="$base_dir/releases/$release_id"
repository_dir="$base_dir/repository"
backup_dir="$base_dir/backups"
state_dir="$base_dir/.deploy/state"
current_link="$base_dir/current"
production_env_path=/opt/job/.env.production
supervisor_config=/etc/supervisor/conf.d/jobcollection.conf
supervisor_disabled=/etc/supervisor/conf.d/jobcollection.conf.disabled
nginx_config=/etc/nginx/sites-available/job.conf
prometheus_config=/etc/prometheus/prometheus.yml
timestamp=$(date -u +%Y%m%dT%H%M%SZ)
database_backup="$backup_dir/job-$release_id.dump"
nginx_backup="$state_dir/nginx-$release_id.conf"
prometheus_backup="$state_dir/prometheus-$release_id.yml"
backend_image="job-backend:$release_id"
frontend_image="job-frontend:$release_id"
previous_release=""
legacy_stopped=0
nginx_changed=0
prometheus_changed=0
supervisor_disabled_now=0
committed=0

mkdir -p "$base_dir/releases" "$backup_dir" "$state_dir"
chmod 700 "$backup_dir" "$state_dir"
mkdir -p /opt/job/certs
chmod 700 /opt/job/certs
exec 9>"$base_dir/.deploy/release.lock"
if ! flock -n 9; then
    echo "Another release is already running." >&2
    exit 1
fi

if [[ -L "$current_link" ]]; then
    previous_release=$(readlink -f "$current_link")
fi

compose_new() {
    (
        cd "$release_dir"
        BACKEND_IMAGE="$backend_image" FRONTEND_IMAGE="$frontend_image" \
            docker compose --env-file .env.production "$@"
    )
}

start_previous_release() {
    [[ -n "$previous_release" && -f "$previous_release/.release.env" ]] || return 1
    (
        cd "$previous_release"
        set -a
        # This file contains only image names generated by this script.
        source .release.env
        set +a
        docker compose --env-file .env.production up -d --remove-orphans \
            api admin worker_realtime frontend
    )
}

start_legacy_services() {
    if [[ -f "$supervisor_disabled" && ! -f "$supervisor_config" ]]; then
        mv "$supervisor_disabled" "$supervisor_config"
        supervisorctl reread >/dev/null || true
        supervisorctl update >/dev/null || true
    fi
    supervisorctl start job-api job-admin job-celery-realtime >/dev/null || true
}

rollback() {
    status=$?
    trap - ERR INT TERM
    if (( committed == 0 )); then
        echo "Release failed; rollback is starting." >&2
        set +e
        if (( nginx_changed == 1 )) && [[ -f "$nginx_backup" ]]; then
            cp "$nginx_backup" "$nginx_config"
            nginx -t && nginx -s reload
        fi
        if (( prometheus_changed == 1 )) && [[ -f "$prometheus_backup" ]]; then
            cp "$prometheus_backup" "$prometheus_config"
            promtool check config "$prometheus_config" >/dev/null 2>&1 || true
            pkill -HUP -x prometheus >/dev/null 2>&1 || true
        fi
        if ! start_previous_release; then
            compose_new stop api admin worker_realtime frontend >/dev/null 2>&1 || true
            if (( legacy_stopped == 1 || supervisor_disabled_now == 1 )); then
                start_legacy_services
            fi
        fi
        echo "Rollback finished." >&2
    fi
    exit "$status"
}
trap rollback ERR INT TERM

echo "[1/8] Fetching exact Git commit $commit"
[[ -f "$production_env_path" ]] || { echo "Missing $production_env_path" >&2; exit 1; }
if [[ ! -d "$repository_dir/.git" ]]; then
    git clone --filter=blob:none --no-checkout "$repository_url" "$repository_dir"
else
    git -C "$repository_dir" remote set-url origin "$repository_url"
fi
(
    cd "$repository_dir"
    git fetch --prune origin
    git cat-file -e "$commit^{commit}"
    [[ $(git rev-parse "$commit^{commit}") == "$commit" ]]
    git worktree prune
    git worktree add --detach "$release_dir" "$commit"
)
install -m 600 "$production_env_path" "$release_dir/.env.production"

host_nginx_template="$release_dir/deploy/nginx/host.conf"
host_prometheus_template="$release_dir/deploy/prometheus/prometheus.yml"
[[ -f "$host_nginx_template" ]] || { echo "Missing host Nginx template" >&2; exit 1; }
[[ -f "$host_prometheus_template" ]] || { echo "Missing Prometheus template" >&2; exit 1; }

printf 'BACKEND_IMAGE=%q\nFRONTEND_IMAGE=%q\n' \
    "$backend_image" "$frontend_image" > "$release_dir/.release.env"
chmod 600 "$release_dir/.release.env"

echo "[2/8] Validating Compose and building immutable images"
compose_new config --quiet
docker build --pull -t "$backend_image" \
    -f "$release_dir/jobCollectionWebApi/backend.Dockerfile" "$release_dir"
docker build --pull -t "$frontend_image" \
    -f "$release_dir/frontend/Dockerfile" "$release_dir"

echo "[3/8] Starting isolated data services"
compose_new up -d db redis
for _ in $(seq 1 30); do
    if [[ $(docker inspect -f '{{.State.Health.Status}}' job_postgres 2>/dev/null || true) == healthy ]] && \
       [[ $(docker inspect -f '{{.State.Health.Status}}' job_redis 2>/dev/null || true) == healthy ]]; then
        break
    fi
    sleep 2
done
[[ $(docker inspect -f '{{.State.Health.Status}}' job_postgres) == healthy ]]
[[ $(docker inspect -f '{{.State.Health.Status}}' job_redis) == healthy ]]

db_user=$(docker exec job_postgres sh -c 'printf %s "$POSTGRES_USER"')
db_name=$(docker exec job_postgres sh -c 'printf %s "$POSTGRES_DB"')

if [[ ! -f "$state_dir/docker-database-initialized" ]]; then
    echo "[4/8] Stopping legacy Job processes and importing the host database"
    supervisorctl stop job-api job-admin job-celery-realtime job-celery-batch job-celery-beat >/dev/null || true
    legacy_stopped=1
    runuser -u postgres -- pg_dump --format=custom "$db_name" > "$database_backup"
    docker exec job_postgres dropdb --if-exists --force -U "$db_user" "$db_name"
    docker exec job_postgres createdb -U "$db_user" "$db_name"
    docker exec -i job_postgres pg_restore --exit-on-error --no-owner --no-privileges \
        -U "$db_user" -d "$db_name" < "$database_backup"
else
    echo "[4/8] Backing up the Docker PostgreSQL database"
    docker exec job_postgres pg_dump --format=custom -U "$db_user" "$db_name" > "$database_backup"
fi
chmod 600 "$database_backup"

echo "[5/8] Running database migrations"
compose_new run --rm migration

echo "[6/8] Starting API, admin, realtime worker, and frontend"
compose_new up -d --remove-orphans api admin worker_realtime frontend
curl --fail --silent --show-error --retry 30 --retry-all-errors --retry-delay 2 \
    http://127.0.0.1:18080/health >/dev/null
curl --fail --silent --show-error --retry 10 --retry-all-errors --retry-delay 2 \
    http://127.0.0.1:18002/admin/ >/dev/null
[[ $(docker inspect -f '{{.State.Running}}' job_worker_realtime) == true ]]

echo "[7/8] Switching host Nginx and Prometheus"
cp "$nginx_config" "$nginx_backup"
sed "s/__SERVER_NAME__/$server_name/g" "$host_nginx_template" > "$nginx_config"
nginx_changed=1
nginx -t
nginx -s reload

cp "$prometheus_config" "$prometheus_backup"
cp "$host_prometheus_template" "$prometheus_config"
prometheus_changed=1
promtool check config "$prometheus_config"
pkill -HUP -x prometheus >/dev/null 2>&1 || true

curl --fail --silent --show-error --retry 10 --retry-all-errors --retry-delay 2 \
    --resolve "$server_name:443:127.0.0.1" "https://$server_name/health" --insecure >/dev/null

echo "[8/8] Recording the release and disabling legacy Supervisor programs"
ln -sfn "$release_dir" "$current_link"
touch "$state_dir/docker-database-initialized"
if [[ -f "$supervisor_config" ]]; then
    mv "$supervisor_config" "$supervisor_disabled"
    supervisor_disabled_now=1
    supervisorctl reread >/dev/null || true
    supervisorctl update >/dev/null || true
fi

committed=1
trap - ERR INT TERM
echo "Release $release_id completed successfully."
BACKEND_IMAGE="$backend_image" FRONTEND_IMAGE="$frontend_image" \
    docker compose -f "$release_dir/docker-compose.yml" \
    --env-file "$release_dir/.env.production" ps
